mnist_classes = ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
cifar_classes = ('plane', 'car', 'bird', 'cat', 'deer',
                 'dog', 'frog', 'horse', 'ship', 'truck')
imagenette_classes = ('tench', 'English springer', 'cassette player', 'chain saw',
                      'church', 'French horn', 'garbage truck', 'gas pump', 'golf ball', 'parachute')

imagenette_classes_map = {
    'n01440764': 'tench, Tinca tinca',
    'n02102040': 'English springer, English springer spaniel',
    'n02979186': 'cassette player',
    'n03000684': 'chain saw, chainsaw',
    'n03028079': 'church, church building',
    'n03394916': 'French horn, horn',
    'n03417042': 'garbage truck, dustcart',
    'n03425413': 'gas pump, gasoline pump, petrol pump, island dispenser',
    'n03445777': 'golf ball',
    'n03888257': 'parachute, chute'
}

coco_classes = [
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bs',
    'train',
    'trck',
    'boat',
    'traffic light',
    'fire hydrant',
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'mbrella',
    'handbag',
    'tie',
    'sitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'srfboard',
    'tennis racket',
    'bottle',
    'wine glass',
    'cp',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'dont',
    'cake',
    'chair',
    'coch',
    'potted plant',
    'bed',
    'dining table',
    'toilet',
    'tv',
    'laptop',
    'mose',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrsh'
]

